version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env.production.local
    restart: unless-stopped
    command: sh -c "yarn prisma db push && yarn start:dev"
    volumes:
      - .:/app
      - /app/node_modules

x-bake:
  platforms:
    - linux/amd64 